// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	_interface "khanhnh-backend/internal/application/interface"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CacheServiceMock is an autogenerated mock type for the CacheService type
type CacheServiceMock struct {
	mock.Mock
}

// Del provides a mock function with given fields: ctx, key
func (_m *CacheServiceMock) Del(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, key, result
func (_m *CacheServiceMock) Get(ctx context.Context, key string, result interface{}) error {
	ret := _m.Called(ctx, key, result)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, key, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObtainLock provides a mock function with given fields: ctx, key, duration
func (_m *CacheServiceMock) ObtainLock(ctx context.Context, key string, duration time.Duration) (_interface.Locker, error) {
	ret := _m.Called(ctx, key, duration)

	if len(ret) == 0 {
		panic("no return value specified for ObtainLock")
	}

	var r0 _interface.Locker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (_interface.Locker, error)); ok {
		return rf(ctx, key, duration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) _interface.Locker); ok {
		r0 = rf(ctx, key, duration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(_interface.Locker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, duration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, key, value, expiration
func (_m *CacheServiceMock) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) error {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCacheServiceMock creates a new instance of CacheServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheServiceMock {
	mock := &CacheServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
