// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "backend/internal/domain/repository"
)

// ProductRepositoryMock is an autogenerated mock type for the ProductRepository type
type ProductRepositoryMock struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, filter
func (_m *ProductRepositoryMock) Get(ctx context.Context, filter *repository.Filter) ([]model.Product, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.Product
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Filter) ([]model.Product, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.Filter) []model.Product); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.Filter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *repository.Filter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetDashboard provides a mock function with given fields: ctx
func (_m *ProductRepositoryMock) GetDashboard(ctx context.Context) ([]model.Dashboard, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboard")
	}

	var r0 []model.Dashboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Dashboard, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Dashboard); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Dashboard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAll provides a mock function with given fields: ctx, products
func (_m *ProductRepositoryMock) SaveAll(ctx context.Context, products []model.Product) error {
	ret := _m.Called(ctx, products)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Product) error); ok {
		r0 = rf(ctx, products)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductRepositoryMock creates a new instance of ProductRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepositoryMock {
	mock := &ProductRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
