// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TokenProviderMock is an autogenerated mock type for the TokenProvider type
type TokenProviderMock[Claims interface{}] struct {
	mock.Mock
}

// Generate provides a mock function with given fields: ctx, claims
func (_m *TokenProviderMock[Claims]) Generate(ctx context.Context, claims *Claims) (string, error) {
	ret := _m.Called(ctx, claims)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *Claims) (string, error)); ok {
		return rf(ctx, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *Claims) string); ok {
		r0 = rf(ctx, claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *Claims) error); ok {
		r1 = rf(ctx, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verify provides a mock function with given fields: ctx, token
func (_m *TokenProviderMock[Claims]) Verify(ctx context.Context, token string) (*Claims, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Claims, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Claims); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenProviderMock creates a new instance of TokenProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenProviderMock[Claims interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenProviderMock[Claims] {
	mock := &TokenProviderMock[Claims]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
